from pyqgraf import qgraf, model

style = r"""
<prologue>
<<!--
 file generated by <program>

<command_loop><command_line_loop> <command_data><end><end>

 You must add x= and y= with suitable vertex positions.
 Some lines may need manual bending to render properly.
-->>
<<feynml>>
<diagram>
  <back>
 <<diagram 
          id="Diagram<diagram_index>"
          incoming="<legs_in>"
          outgoing="<legs_out>"
          sign="<sign>"
          symmmetry_factor="<symmetry_factor>"
 >>

<vertex_loop> 
  <<vertex id="Vert<vertex_index>">>
  <</vertex>>
<end>

<in_loop>
  <<leg id="In<in_index>">>  
        <<name>><field><</name>>
        <<sense>>incoming<</sense>>
        <<target>>Vert<vertex_index><</target>>
        <<momentum>>
          <<name>><momentum><</name>>
        <</momentum>>
  <</leg>>
<end>

<out_loop> 
  <<leg id="Out<out_index>">>  
        <<name>><field><</name>>
        <<sense>>outgoing<</sense>>
        <<target>>Vert<vertex_index><</target>>
        <<momentum>>
          <<name>><momentum><</name>>
        <</momentum>>
  <</leg>>
<end>

<propagator_loop> 
  <<propagator id="Prop<propagator_index>">>  
        <<name>><field><</name>>
        <<source>>Vert<dual-vertex_index><</source>>
        <<target>>Vert<vertex_index><</target>>
        <<momentum>>
          <<name>><momentum><</name>>
        <</momentum>>
  <</propagator>>
<end>

 <</diagram>>
<epilogue>
<</feynml>>

<<!-- end -->>
<exit>
"""


def test_run():
    qgraf.install()
    xml_string = qgraf.run(
        "nu_e[p1], nu_e_bar[p2]",
        "nu_e[p3], nu_e_bar[p4]",
        loops=1,
        loop_momentum="l",
        model=model.gws_UnitaryGauge_reduced,
        style=style,
    )


def test_run_3_6_5():
    qgraf.install("3.6.5")
    xml_string = qgraf.run(
        "e_minus[p1]",
        "e_minus[p2]",
        loops=1,
        loop_momentum="l",
        model=model.qed,
        style=style,
    )


def test_run_3_4_2():
    qgraf.install("3.4.2")
    xml_string = qgraf.run(
        "nu_e[p1], nu_e_bar[p2]",
        "nu_e[p3], nu_e_bar[p4]",
        loops=1,
        loop_momentum="l",
        model=model.gws_UnitaryGauge,
        style=style,
    )
